name: manual build

on:
  workflow_dispatch:
    inputs:
      buildtype:
        type: choice
        description: Build Type
        options:
        - Release
        - Debug

jobs:
  android:
    name: Android Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
          cache: gradle

      - name: Build APK
        run: |
          cd android
          ./gradlew "assembleGit${{ github.event.inputs.buildtype }}"
          
          LOWER_TYPE=$(echo "${{ github.event.inputs.buildtype }}" | tr '[:upper:]' '[:lower:]')
          cp app/build/outputs/apk/git/$LOWER_TYPE/*.apk ../app-$LOWER_TYPE.apk

      - name: Upload APK to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Android-${{ github.event.inputs.buildtype }}
          path: app-*.apk
